{{- define "jobSpec" }}
spec:
  {{- if .Values.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
  {{- end}}
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceAccountName: {{ include "cronjob.serviceAccountName" . }}
  {{- with .Values.podSecurityContext }}
  securityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  containers:
    - name: {{ .Chart.Name }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{- with .Values.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.args }}
      args:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.command }}
      command:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.envSecret }}
      envFrom:
      - secretRef:
          name: {{ .Values.envSecret }}
      {{- end }}
      {{- if .Values.envConfigMap }}
      - configMapRef:
          name: {{ .Values.envConfigMap }}
      {{- end }}
      {{- if .Values.env }}
      env:
      {{- range $key, $val := .Values.env }}
      - name: {{ $key | upper }}
        value: {{ $val }}
      {{- end }}
      {{- end }}
      {{- if .Values.fileSecret.name }}
      volumeMounts:
        - mountPath: {{ .Values.fileSecret.mountPath }}
          name: filesecrets
      {{- end }}
  restartPolicy: {{ .Values.restartPolicy }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.fileSecret.name }}
  volumes:
    - name: filesecrets
      secret:
        secretName: {{ .Values.fileSecret.name }}
  {{- end }}
{{- end }}
