{{- if .Values.singleRun }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
    {{- include "cronjob.selectorLabels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    {{- include "jobSpec" . | indent 4}}
{{- end }}
