apiVersion: v2
name: gangway
version: 0.0.2
description: An application that can be used to easily enable authentication flows via OIDC for a kubernetes cluster.
type: application
home: https://github.com/heptiolabs/gangway
keywords:
  - authentication
  - k8s
  - oidc
maintainers:
- name: City-of-Helsinki
appVersion: v3.2.0
