---
# Source: cronjob/templates/cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: testcron-cronjob
  labels:
    helm.sh/chart: cronjob-0.1.0
    app.kubernetes.io/name: cronjob
    app.kubernetes.io/instance: testcron
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: cronjob
            app.kubernetes.io/instance: testcron
        spec:
          serviceAccountName: testcron-cronjob
          containers:
            - name: cronjob
              image: "busybox:latest"
              imagePullPolicy: IfNotPresent
              args:
              - -c
              - date; echo Hello from the Kubernetes cluster
              command:
              - /bin/sh
              envFrom:
              env:
          restartPolicy: OnFailure
