---
# Source: cronjob/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testcron-cronjob
  labels:
    helm.sh/chart: cronjob-0.1.0
    app.kubernetes.io/name: cronjob
    app.kubernetes.io/instance: testcron
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
