apiVersion: v2
name: weavescope
description: |
  A Helm chart for Kubernetes to deploy Weave scope.

  Based on manifests from https://github.com/alexdmoss/weave-scope.
keywords:
- weavescope
- monitoring
- maintenance
sources:
- https://github.com/weaveworks/scope
type: application
version: 0.1.3
appVersion: 1.13.2
maintainers:
- name: Hi-Fi
- name: City-of-Helsinki
