apiVersion: v2
name: external-service-monitoring
description: Chart to create servicemonitors that scrape external services utilizing [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator)
type: application

version: 0.1.0

appVersion: 1.0.0

maintainers:
- name: Hi-Fi
- name: City-of-Helsinki
