apiVersion: v2
name: oauth2-proxy
description: |
  A reverse proxy that provides authentication with Google, Github or other providers

  Original chart at https://github.com/helm/charts/tree/master/stable/oauth2-proxy.
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
sources:
- https://github.com/oauth2-proxy/oauth2-proxy
type: application
version: 7.1.4
appVersion: "v7.1.3"
maintainers:
- name: Hi-Fi
- name: City-of-Helsinki
