apiVersion: v2
name: dex
version: 0.0.1
description: OpenID Connect Identity (OIDC) and OAuth 2.0 Provider with Pluggable Connectors
type: application
home: https://github.com/dexidp/dex
keywords:
  - authentication
  - idp
  - oidc
maintainers:
- name: City-of-Helsinki
appVersion: "v2.30.2"
