{{- if and .Values.htpasswdFile.enabled (not .Values.htpasswdFile.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}-htpasswd-file
type: Opaque
stringData:
  users.txt: |-
    {{- range $entries := .Values.htpasswdFile.entries }}
    {{ $entries }}
    {{- end -}}
{{- end }}
