{{- if and .Values.config.google (not .Values.config.google.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}-google
type: Opaque
data:
  service-account.json: {{ .serviceAccountJson }}
{{- end -}}
