apiVersion: v2
name: managed-k8s-oidc-auth
description: A Helm chart for Kubernetes to deploy services needed for OIDC access to managed clusters (AKS, ESK, GKE)

type: application

version: 0.1.7

appVersion: 1.0.0

maintainers:
- name: Hi-Fi
- name: City-of-Helsinki

dependencies:
- name: kube-oidc-proxy
  version: 0.3.4
  repository: "https://city-of-helsinki.github.io/helm-charts/"
- name: dex
  version: 0.0.1
  repository: "https://city-of-helsinki.github.io/helm-charts/"
  condition: dex.enabled
- name: gangway
  version: 0.0.2
  repository: "https://city-of-helsinki.github.io/helm-charts/"
