apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weavescope.fullname" . }}-app
  labels:
    weave-cloud-component: scope
    weave-scope-component: app
    {{- include "weavescope.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      weave-cloud-component: scope
      weave-scope-component: app
      {{- include "weavescope.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        weave-cloud-component: scope
        weave-scope-component: app
        {{- include "weavescope.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-app
          args:
          - '--mode=app'
          {{-  if not .Values.weavenet }}
          - --weave=false
          {{- end }}
          {{-  if .Values.readonly }}
          - --probe.no-controls=true
          {{- end }}
          command:
          - /home/weave/scope
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
          - containerPort: 4040
            protocol: TCP
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
