apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
  name: {{ include "weavescope.fullname" . }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  hostPID: true
  hostNetwork: true
  requiredDropCapabilities:
  - ALL
  allowedCapabilities:
  - 'NET_BIND_SERVICE'
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - hostPath
  readOnlyRootFilesystem: true
