kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "weavescope.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: weave-scope
subjects:
- kind: ServiceAccount
  name: {{ include "weavescope.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "weavescope.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
