apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gangway.fullname" . }}
  labels:
    {{- include "gangway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gangway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubernetes.io/configuration-checksum: {{ .Values.config | toYaml | sha256sum | trunc 32 }}
      labels:
        {{- include "gangway.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "gangway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "gangway.fullname" . }}
        {{- if or .Values.trustedCA.content .Values.trustedCA.secretName }}
        - name: trusted-ca
          secret:
            secretName: {{ if .Values.trustedCA.secretName }}{{ .Values.trustedCA.secretName }}{{ else }}{{ include "gangway.fullname" . }}-trusted-ca{{ end }}
            items:
              - key: tls.crt
                path: tls.crt
        {{- end }}
        {{- if .Values.customHTMLTemplates.enabled }}
        - name: templates
          configMap:
            name: {{ include "gangway.fullname" . }}-templates
        {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/gangway
          args:
            - --config
            - /etc/gangway/config/gangway.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "gangway.fullname" . }}-env
            - secretRef:
                {{- if .Values.existingSecret }}
                name: {{ .Values.existingSecret }}
                {{- else }}
                name: {{ include "gangway.fullname" . }}
                {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/gangway/config
            {{- if or .Values.trustedCA.content .Values.trustedCA.secretName }}
            - name: trusted-ca
              mountPath: /etc/gangway/trusted-ca
            {{- end }}
            {{- if .Values.customHTMLTemplates.enabled }}
            - name: templates
              mountPath: /etc/gangway/templates
            {{- end }}
          livenessProbe:
            httpGet:
              path: /login
              port: http
              httpHeaders:
                - name: X-K8S-HEALTH-CHECK
                  value: live
          readinessProbe:
            httpGet:
              path: /login
              port: http
              httpHeaders:
                - name: X-K8S-HEALTH-CHECK
                  value: ready
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
