{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gangway.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $stableApi := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"}}
{{- if $stableApi -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gangway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            {{- if $stableApi }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $stableApi }}
              service:
                name: {{ $fullName }}
                port:
                  name: https
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: https
              {{- end }}
        {{- end }}
    {{- end -}}
  {{- end }}
