{{- if .Values.RBAC.developerGroups -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-oidc-proxy.fullname" . }}-oidc-developers
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/attach"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
---
{{- end }}
{{- if .Values.RBAC.viewerGroups -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-oidc-proxy.fullname" . }}-oidc-viewers
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "namespaces"]
  verbs: ["get", "list"]
{{- end }}
