name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Add dependency chart repos
        run: |
          helm repo add gabibbo97 https://gabibbo97.github.io/charts/
          helm repo add jetstack https://charts.jetstack.io
          helm repo add city-of-helsinki https://city-of-helsinki.github.io/managed-k8s-oidc-auth/

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          # from https://github.com/instrumenta/kubernetes-json-schema
          - v1.16.4
          - v1.17.4
          - v1.18.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Add dependency chart repos
        run: |
          helm repo add gabibbo97 https://gabibbo97.github.io/charts/
          helm repo add jetstack https://charts.jetstack.io
          helm repo add city-of-helsinki https://city-of-helsinki.github.io/managed-k8s-oidc-auth/

      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          # from https://hub.docker.com/r/kindest/node/tags
          - v1.16.15
          - v1.17.11
          - v1.18.8
          - v1.19.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Add dependency chart repos
        run: |
          helm repo add gabibbo97 https://gabibbo97.github.io/charts/
          helm repo add jetstack https://charts.jetstack.io
          helm repo add city-of-helsinki https://city-of-helsinki.github.io/managed-k8s-oidc-auth/

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.1.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Set up cert-manager
        run: |
          kubectl create namespace cert-manager
          helm install \
            cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --version v1.1.0 \
            --set installCRDs=true \
            --wait
          cat <<EOF > test-resources.yaml
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: selfsigned-issuer
          spec:
            selfSigned: {}
          EOF
          kubectl apply -f test-resources.yaml
      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml
